---
## Add Java and OpenShift CLI Stack

- name: create custom stack for jdk and openshift cli
  uri:
    url: http://che-{{ project_name }}.{{ apps_hostname_suffix }}/api/stack
    method: POST
    body: "{{ lookup('file','files/che-stack.json') }}"
    body_format: json
    status_code: 200,201
